using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class recorrencia : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1) DROP FK somente se existir
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE c.conname = 'FK_Appointments_Professionals_ProfessionalId'
          AND n.nspname = 'public'
          AND t.relname = 'Appointments'
    ) THEN
        ALTER TABLE ""Appointments""
        DROP CONSTRAINT ""FK_Appointments_Professionals_ProfessionalId"";
    END IF;
END $$;
");

            // 2) DROP INDEX somente se existir
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname = 'public'
          AND indexname  = 'IX_Appointments_ProfessionalId'
    ) THEN
        DROP INDEX ""IX_Appointments_ProfessionalId"";
    END IF;
END $$;
");

            // 3) DROP COLUMN somente se existir
            migrationBuilder.Sql(@"ALTER TABLE ""Appointments"" DROP COLUMN IF EXISTS ""ProfessionalId"";");

            // 4) Add columns com IF NOT EXISTS (evita quebrar se já estiver aplicado)
            migrationBuilder.Sql(@"ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""Onboarding"" boolean NOT NULL DEFAULT FALSE;");
            migrationBuilder.Sql(@"ALTER TABLE ""Appointments"" ADD COLUMN IF NOT EXISTS ""ProfessionalIdsData"" text NULL;");

            // 5) Create table IF NOT EXISTS (evita quebrar em re-run)
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""AppointmentRecurrenceExceptions"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""SeriesId"" uuid NOT NULL,
    ""OccurrenceStart"" timestamptz NOT NULL,
    ""OccurrenceEnd"" timestamptz NOT NULL,
    ""IsCancelled"" boolean NOT NULL DEFAULT FALSE,
    ""OverrideTitle"" text NULL,
    ""OverrideAddress"" text NULL,
    ""OverrideNotes"" text NULL,
    ""OverrideStart"" timestamptz NULL,
    ""OverrideEnd"" timestamptz NULL,
    ""OverrideStatus"" integer NULL,
    ""OverrideType"" integer NULL,
    ""OverrideProfessionalIdsData"" text NULL,
    ""CreatedDate"" timestamptz NOT NULL DEFAULT now(),
    ""UpdatedDate"" timestamptz NOT NULL DEFAULT now()
);
");

            // Índices úteis (com IF NOT EXISTS)
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AppointmentRecurrenceExceptions_SeriesId"" ON ""AppointmentRecurrenceExceptions"" (""SeriesId"");");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AppointmentRecurrenceExceptions_SeriesId_OccurrenceStart"" ON ""AppointmentRecurrenceExceptions"" (""SeriesId"", ""OccurrenceStart"");");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AppointmentRecurrenceExceptions");

            migrationBuilder.DropColumn(
                name: "Onboarding",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "ProfessionalIdsData",
                table: "Appointments");

            migrationBuilder.AddColumn<int>(
                name: "ProfessionalId",
                table: "Appointments",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_ProfessionalId",
                table: "Appointments",
                column: "ProfessionalId");

            migrationBuilder.AddForeignKey(
                name: "FK_Appointments_Professionals_ProfessionalId",
                table: "Appointments",
                column: "ProfessionalId",
                principalTable: "Professionals",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
