using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class AddAppointmentReviewRequestDispatches : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create table if missing (some DBs may already have partial schema).
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'AppointmentReviewRequestDispatches'
    ) THEN
        CREATE TABLE ""AppointmentReviewRequestDispatches"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""CompanyId"" integer NOT NULL,
            ""AppointmentCompletionId"" integer NOT NULL,
            ""ReviewId"" integer NOT NULL,
            ""CustomerId"" integer NOT NULL,
            ""RecipientEmail"" text NOT NULL,
            ""Status"" integer NOT NULL DEFAULT 0,
            ""AttemptCount"" integer NOT NULL DEFAULT 0,
            ""LastAttemptAtUtc"" timestamp with time zone NULL,
            ""SentAtUtc"" timestamp with time zone NULL,
            ""LastError"" text NULL,
            ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT now(),
            ""UpdatedDate"" timestamp with time zone NOT NULL DEFAULT now()
        );
    END IF;
END$$;
");

            // Unique index (idempotency)
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'IX_AppointmentReviewRequestDispatches_AppointmentCompletionId'
          AND n.nspname = 'public'
    ) THEN
        CREATE UNIQUE INDEX ""IX_AppointmentReviewRequestDispatches_AppointmentCompletionId""
            ON ""AppointmentReviewRequestDispatches"" (""AppointmentCompletionId"");
    END IF;
END$$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'IX_AppointmentReviewRequestDispatches_Status_SentAtUtc'
          AND n.nspname = 'public'
    ) THEN
        CREATE INDEX ""IX_AppointmentReviewRequestDispatches_Status_SentAtUtc""
            ON ""AppointmentReviewRequestDispatches"" (""Status"", ""SentAtUtc"");
    END IF;
END$$;
");

            // FKs if missing
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_AppointmentReviewRequestDispatches_AppointmentCompletions_AppointmentCompletionId'
    ) THEN
        ALTER TABLE ""AppointmentReviewRequestDispatches""
        ADD CONSTRAINT ""FK_AppointmentReviewRequestDispatches_AppointmentCompletions_AppointmentCompletionId""
        FOREIGN KEY (""AppointmentCompletionId"") REFERENCES ""AppointmentCompletions"" (""Id"")
        ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_AppointmentReviewRequestDispatches_Reviews_ReviewId'
    ) THEN
        ALTER TABLE ""AppointmentReviewRequestDispatches""
        ADD CONSTRAINT ""FK_AppointmentReviewRequestDispatches_Reviews_ReviewId""
        FOREIGN KEY (""ReviewId"") REFERENCES ""Reviews"" (""Id"")
        ON DELETE CASCADE;
    END IF;
END$$;
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Best-effort rollback
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AppointmentReviewRequestDispatches_AppointmentCompletions_AppointmentCompletionId') THEN
        ALTER TABLE ""AppointmentReviewRequestDispatches"" DROP CONSTRAINT ""FK_AppointmentReviewRequestDispatches_AppointmentCompletions_AppointmentCompletionId"";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AppointmentReviewRequestDispatches_Reviews_ReviewId') THEN
        ALTER TABLE ""AppointmentReviewRequestDispatches"" DROP CONSTRAINT ""FK_AppointmentReviewRequestDispatches_Reviews_ReviewId"";
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'IX_AppointmentReviewRequestDispatches_Status_SentAtUtc'
          AND n.nspname = 'public'
    ) THEN
        DROP INDEX ""IX_AppointmentReviewRequestDispatches_Status_SentAtUtc"";
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'IX_AppointmentReviewRequestDispatches_AppointmentCompletionId'
          AND n.nspname = 'public'
    ) THEN
        DROP INDEX ""IX_AppointmentReviewRequestDispatches_AppointmentCompletionId"";
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'AppointmentReviewRequestDispatches'
    ) THEN
        DROP TABLE ""AppointmentReviewRequestDispatches"";
    END IF;
END$$;
");
        }
    }
}
