using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class AddHouseNotesAndServiceIssuess : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
ALTER TABLE ""CustomerAddresses"" ADD COLUMN IF NOT EXISTS ""HouseAccessNotes"" character varying(600);
ALTER TABLE ""CustomerAddresses"" ADD COLUMN IF NOT EXISTS ""HouseGateCode"" character varying(120);
ALTER TABLE ""CustomerAddresses"" ADD COLUMN IF NOT EXISTS ""HouseHasPets"" boolean;
ALTER TABLE ""CustomerAddresses"" ADD COLUMN IF NOT EXISTS ""HousePetNotes"" character varying(600);
ALTER TABLE ""CustomerAddresses"" ADD COLUMN IF NOT EXISTS ""HouseRestrictionsNotes"" character varying(800);
ALTER TABLE ""CustomerAddresses"" ADD COLUMN IF NOT EXISTS ""HousePriorityNotes"" character varying(800);
ALTER TABLE ""CustomerAddresses"" ADD COLUMN IF NOT EXISTS ""HousePhotoUrlsJson"" jsonb;

ALTER TABLE ""Appointments"" ADD COLUMN IF NOT EXISTS ""HouseNotesSnapshotJson"" jsonb;

CREATE TABLE IF NOT EXISTS ""ServiceIssues"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT NOW(),
    ""UpdatedDate"" timestamp with time zone NOT NULL DEFAULT NOW(),
    ""CompanyId"" integer NOT NULL,
    ""AppointmentId"" integer NOT NULL,
    ""CustomerId"" integer NULL,
    ""CustomerAddressId"" integer NULL,
    ""ProfessionalId"" integer NULL,
    ""ReportedByUserId"" integer NOT NULL,
    ""ReviewedByUserId"" integer NULL,
    ""Type"" character varying(60) NOT NULL,
    ""Status"" character varying(30) NOT NULL,
    ""Summary"" character varying(200) NOT NULL,
    ""Description"" character varying(2000) NULL,
    ""InternalNotes"" character varying(1000) NULL,
    ""EstimatedAmount"" numeric(18,2) NULL,
    ""ApprovedAmount"" numeric(18,2) NULL,
    ""PhotoUrlsJson"" jsonb NULL,
    ""ResolvedAtUtc"" timestamp with time zone NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ServiceIssues_Companies_CompanyId'
    ) THEN
        ALTER TABLE ""ServiceIssues""
            ADD CONSTRAINT ""FK_ServiceIssues_Companies_CompanyId""
            FOREIGN KEY (""CompanyId"") REFERENCES ""Companies"" (""Id"") ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ServiceIssues_Appointments_AppointmentId'
    ) THEN
        ALTER TABLE ""ServiceIssues""
            ADD CONSTRAINT ""FK_ServiceIssues_Appointments_AppointmentId""
            FOREIGN KEY (""AppointmentId"") REFERENCES ""Appointments"" (""Id"") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ServiceIssues_Customers_CustomerId'
    ) THEN
        ALTER TABLE ""ServiceIssues""
            ADD CONSTRAINT ""FK_ServiceIssues_Customers_CustomerId""
            FOREIGN KEY (""CustomerId"") REFERENCES ""Customers"" (""Id"") ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ServiceIssues_CustomerAddresses_CustomerAddressId'
    ) THEN
        ALTER TABLE ""ServiceIssues""
            ADD CONSTRAINT ""FK_ServiceIssues_CustomerAddresses_CustomerAddressId""
            FOREIGN KEY (""CustomerAddressId"") REFERENCES ""CustomerAddresses"" (""Id"") ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ServiceIssues_Professionals_ProfessionalId'
    ) THEN
        ALTER TABLE ""ServiceIssues""
            ADD CONSTRAINT ""FK_ServiceIssues_Professionals_ProfessionalId""
            FOREIGN KEY (""ProfessionalId"") REFERENCES ""Professionals"" (""Id"") ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ServiceIssues_Users_ReportedByUserId'
    ) THEN
        ALTER TABLE ""ServiceIssues""
            ADD CONSTRAINT ""FK_ServiceIssues_Users_ReportedByUserId""
            FOREIGN KEY (""ReportedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_ServiceIssues_Users_ReviewedByUserId'
    ) THEN
        ALTER TABLE ""ServiceIssues""
            ADD CONSTRAINT ""FK_ServiceIssues_Users_ReviewedByUserId""
            FOREIGN KEY (""ReviewedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ""IX_ServiceIssues_AppointmentId"" ON ""ServiceIssues"" (""AppointmentId"");
CREATE INDEX IF NOT EXISTS ""IX_ServiceIssues_CompanyId_Status_CreatedDate"" ON ""ServiceIssues"" (""CompanyId"", ""Status"", ""CreatedDate"");
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP INDEX IF EXISTS ""IX_ServiceIssues_AppointmentId"";
DROP INDEX IF EXISTS ""IX_ServiceIssues_CompanyId_Status_CreatedDate"";
DROP TABLE IF EXISTS ""ServiceIssues"";
ALTER TABLE ""Appointments"" DROP COLUMN IF EXISTS ""HouseNotesSnapshotJson"";
ALTER TABLE ""CustomerAddresses"" DROP COLUMN IF EXISTS ""HousePhotoUrlsJson"";
ALTER TABLE ""CustomerAddresses"" DROP COLUMN IF EXISTS ""HousePriorityNotes"";
ALTER TABLE ""CustomerAddresses"" DROP COLUMN IF EXISTS ""HouseRestrictionsNotes"";
ALTER TABLE ""CustomerAddresses"" DROP COLUMN IF EXISTS ""HousePetNotes"";
ALTER TABLE ""CustomerAddresses"" DROP COLUMN IF EXISTS ""HouseHasPets"";
ALTER TABLE ""CustomerAddresses"" DROP COLUMN IF EXISTS ""HouseGateCode"";
ALTER TABLE ""CustomerAddresses"" DROP COLUMN IF EXISTS ""HouseAccessNotes"";
");
        }
    }
}
