using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class AddCustomerAddressesAndAppointmentCustomerAddress : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""CustomerAddresses"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""CustomerId"" integer NOT NULL,
                    ""Label"" text NULL,
                    ""AddressLine1"" text NOT NULL DEFAULT '',
                    ""AddressLine2"" text NULL,
                    ""City"" text NOT NULL DEFAULT '',
                    ""State"" text NOT NULL DEFAULT '',
                    ""ZipCode"" text NULL,
                    ""Observations"" text NULL,
                    ""Ticket"" numeric NULL,
                    ""Frequency"" integer NULL,
                    ""PaymentMethod"" integer NULL,
                    ""IsPrimary"" boolean NOT NULL DEFAULT FALSE,
                    ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedDate"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_CustomerAddresses"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_CustomerAddresses_Customers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""Customers"" (""Id"") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_CustomerAddresses_CustomerId"" ON ""CustomerAddresses"" (""CustomerId"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""UX_CustomerAddresses_PrimaryPerCustomer"" ON ""CustomerAddresses"" (""CustomerId"") WHERE ""IsPrimary"" = TRUE;

                INSERT INTO ""CustomerAddresses"" (""CustomerId"", ""Label"", ""AddressLine1"", ""AddressLine2"", ""City"", ""State"", ""ZipCode"", ""Observations"", ""Ticket"", ""Frequency"", ""PaymentMethod"", ""IsPrimary"", ""CreatedDate"", ""UpdatedDate"")
                SELECT c.""Id"", 'Primary', COALESCE(NULLIF(c.""Address"", ''), ''), NULL, COALESCE(NULLIF(c.""City"", ''), ''), COALESCE(NULLIF(c.""State"", ''), ''), c.""ZipCode"", c.""Observations"", c.""Ticket"", c.""Frequency"", c.""PaymentMethod"", TRUE, NOW(), NOW()
                FROM ""Customers"" c
                WHERE NOT EXISTS (
                    SELECT 1 FROM ""CustomerAddresses"" ca WHERE ca.""CustomerId"" = c.""Id"" AND ca.""IsPrimary"" = TRUE
                );

                ALTER TABLE ""Appointments"" ADD COLUMN IF NOT EXISTS ""CustomerAddressId"" integer NULL;
                CREATE INDEX IF NOT EXISTS ""IX_Appointments_CustomerAddressId"" ON ""Appointments"" (""CustomerAddressId"");
                DO $$ BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints
                        WHERE constraint_name = 'FK_Appointments_CustomerAddresses_CustomerAddressId'
                    ) THEN
                        ALTER TABLE ""Appointments"" ADD CONSTRAINT ""FK_Appointments_CustomerAddresses_CustomerAddressId"" FOREIGN KEY (""CustomerAddressId"") REFERENCES ""CustomerAddresses"" (""Id"") ON DELETE SET NULL;
                    END IF;
                END $$;

                UPDATE ""Appointments"" a
                SET ""CustomerAddressId"" = ca.""Id""
                FROM ""CustomerAddresses"" ca
                WHERE a.""CustomerAddressId"" IS NULL
                  AND a.""CustomerId"" IS NOT NULL
                  AND ca.""CustomerId"" = a.""CustomerId""
                  AND ca.""IsPrimary"" = TRUE;

                ALTER TABLE ""AppointmentRecurrenceExceptions"" ADD COLUMN IF NOT EXISTS ""OverrideCustomerAddressId"" integer NULL;
                CREATE INDEX IF NOT EXISTS ""IX_AppointmentRecurrenceExceptions_OverrideCustomerAddressId"" ON ""AppointmentRecurrenceExceptions"" (""OverrideCustomerAddressId"");
                DO $$ BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints
                        WHERE constraint_name = 'FK_AppointmentRecurrenceExceptions_CustomerAddresses_OverrideCustomerAddressId'
                    ) THEN
                        ALTER TABLE ""AppointmentRecurrenceExceptions"" ADD CONSTRAINT ""FK_AppointmentRecurrenceExceptions_CustomerAddresses_OverrideCustomerAddressId"" FOREIGN KEY (""OverrideCustomerAddressId"") REFERENCES ""CustomerAddresses"" (""Id"") ON DELETE SET NULL;
                    END IF;
                END $$;

                ALTER TABLE ""AppointmentCompletions"" ADD COLUMN IF NOT EXISTS ""CustomerAddressIdSnapshot"" integer NULL;
                ALTER TABLE ""AppointmentCompletions"" ADD COLUMN IF NOT EXISTS ""CustomerAddressSnapshot"" text NULL;
                ALTER TABLE ""AppointmentCompletions"" ADD COLUMN IF NOT EXISTS ""PaymentMethodSnapshot"" text NULL;
                ALTER TABLE ""AppointmentCompletions"" ADD COLUMN IF NOT EXISTS ""FrequencySnapshot"" text NULL;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""Appointments"" DROP COLUMN IF EXISTS ""CustomerAddressId"";
                ALTER TABLE ""AppointmentRecurrenceExceptions"" DROP COLUMN IF EXISTS ""OverrideCustomerAddressId"";
                ALTER TABLE ""AppointmentCompletions"" DROP COLUMN IF EXISTS ""CustomerAddressIdSnapshot"";
                ALTER TABLE ""AppointmentCompletions"" DROP COLUMN IF EXISTS ""CustomerAddressSnapshot"";
                ALTER TABLE ""AppointmentCompletions"" DROP COLUMN IF EXISTS ""PaymentMethodSnapshot"";
                ALTER TABLE ""AppointmentCompletions"" DROP COLUMN IF EXISTS ""FrequencySnapshot"";
                DROP TABLE IF EXISTS ""CustomerAddresses"";
            ");
        }
    }
}
