using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class AddAppointmentMessageLogs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent migration (Postgres)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AppointmentMessageLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""CreatedDate"" timestamp without time zone NOT NULL DEFAULT now(),
                    ""UpdatedDate"" timestamp without time zone NOT NULL DEFAULT now(),

                    ""AppointmentId"" integer NOT NULL,
                    ""Kind"" integer NOT NULL,
                    ""Channel"" integer NOT NULL,
                    ""Status"" integer NOT NULL,

                    ""ScheduledForUtc"" timestamp without time zone NULL,
                    ""SentAtUtc"" timestamp without time zone NULL,
                    ""Attempt"" integer NOT NULL DEFAULT 0,

                    ""RequestedByUserId"" integer NULL,
                    ""RequestedByRole"" character varying(32) NULL,

                    ""RecipientEmail"" character varying(256) NULL,
                    ""RecipientPhoneE164"" character varying(32) NULL,

                    ""Subject"" character varying(256) NULL,
                    ""BodyText"" text NULL,
                    ""TemplateKey"" character varying(128) NULL,
                    ""PayloadJson"" text NULL,

                    ""Provider"" character varying(64) NOT NULL DEFAULT '',
                    ""ProviderMessageId"" character varying(128) NULL,
                    ""ProviderStatus"" character varying(128) NULL,

                    ""LastError"" text NULL,
                    ""LastErrorRaw"" text NULL,

                    CONSTRAINT ""PK_AppointmentMessageLogs"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AppointmentMessageLogs_Appt_Kind_Channel_Created"" ON ""AppointmentMessageLogs"" (""AppointmentId"", ""Kind"", ""Channel"", ""CreatedDate"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_AppointmentMessageLogs_ProviderMessageId"" ON ""AppointmentMessageLogs"" (""ProviderMessageId"");");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_AppointmentMessageLogs_Appt_Kind_Channel_Created"";");
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_AppointmentMessageLogs_ProviderMessageId"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""AppointmentMessageLogs"";");
        }
    }
}
